"""Base class for recipe import services across all platforms."""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src.ai_recipe_engine.ai_recipe_service import TechniqueExtractionService
from src.database.database_service import DatabaseService
from src.database.schemas.recipe_schema import LoadingStatus, StoredRecipe
from src.recipe_import_service.schemas.import_schema import (
    ImportResponse,
    LlmOutputFormat,
    PollingRequest,
    PollingResponse,
    RecipeStatus,
)
from src.shared.llm_service.mistral import MistralModels, MistralService
from src.util.template_formatter import TemplateFormatter

logger = logging.getLogger(__name__)


class BaseImportService:
    """Base class for recipe import services (TikTok, YouTube, Instagram, etc.)."""

    # Subclasses should define these
    MODEL: MistralModels
    TEMPLATE_PATH: Path

    def __init__(
        self,
        mistral_service: MistralService,
        technique_extraction_service: TechniqueExtractionService,
        db_service: DatabaseService,
    ) -> None:
        """Initialize base import service.

        Args:
            mistral_service: Mistral LLM service for recipe extraction
            technique_extraction_service: Service for extracting techniques from recipes
            db_service: Database service for recipe and user operations
        """
        self.mistral_service = mistral_service
        self.technique_extraction_service = technique_extraction_service
        self.db_service = db_service

    async def import_recipe(
        self,
        url: str,
        recipe_id: str,
        user_id: str,
        mock: bool = False,
        background: bool = False,
    ) -> ImportResponse:
        """Import recipe from URL with validation and database storage.

        Args:
            url: URL from any supported platform
            recipe_id: Recipe ID (generated by caller)
            user_id: User ID for saving the recipe
            mock: If True, uses mock data instead of real API calls
            background: If True, runs the import in the background

        Returns:
            ImportResponse with recipe data or no_recipe_found flag

        Raises:
            ValueError: If URL is empty or invalid
            Exception: If recipe extraction or database operation fails
        """
        try:
            return await self._import_recipe(url, recipe_id, user_id, mock)
        except:
            logger.error(
                f"Failed to import recipe {recipe_id} from {url}", exc_info=True
            )
            # Remove from loading_recipes after successful save
            await self.db_service.set_loading_recipe_err(user_id, recipe_id)

            raise

    async def _import_recipe(
        self,
        url: str,
        recipe_id: str,
        user_id: str,
        mock: bool = False,
    ) -> ImportResponse:
        """Import recipe from URL with validation and database storage.

        Args:
            url: URL from any supported platform
            recipe_id: Recipe ID (generated by caller)
            user_id: User ID for saving the recipe
            db_service: Database service instance for saving recipes
            mock: If True, uses mock data instead of real API calls

        Returns:
            ImportResponse with recipe data or no_recipe_found flag

        Raises:
            ValueError: If URL is empty or invalid
            Exception: If recipe extraction or database operation fails
        """
        if not url.strip():
            raise ValueError("URL cannot be empty")

        # Extract recipe and thumbnail from platform
        recipe, thumbnail_url = await self._url_to_text_recipe(url, mock=mock)

        # Return early if no recipe found
        if recipe is None:
            await self.db_service.update_loading_recipe_status(
                user_id, recipe_id, LoadingStatus.ERROR
            )
            return ImportResponse(
                recipe=None, no_recipe_found=True, recipe_id=recipe_id
            )

        # Update status to extracting_techniques
        await self.db_service.update_loading_recipe_status(
            user_id, recipe_id, LoadingStatus.EXTRACTING_TECHNIQUES
        )

        # Extract techniques from the recipe text
        extraction_result = await self.technique_extraction_service.extract_techniques(
            recipe
        )

        # Create and save recipe to database
        creation_time = datetime.now(timezone.utc)
        stored_recipe = StoredRecipe(
            **extraction_result.model_dump(),
            recipe_id=recipe_id,
            user_id=user_id,
            source_url=url,
            thumbnail_url=thumbnail_url,
            created_at=creation_time,
        )

        recipe_display = await self.db_service.add_recipe_to_user(
            user_id, stored_recipe
        )

        # Remove from loading_recipes after successful save
        await self.db_service.remove_loading_recipe(user_id, recipe_id)

        logger.info(f"Recipe '{stored_recipe.recipe_name}' saved for user {user_id}")
        return ImportResponse(
            recipe=recipe_display,
            no_recipe_found=False,
            recipe_id=recipe_id,
        )

    async def _url_to_text_recipe(
        self, url: str, mock: bool = False
    ) -> tuple[Optional[str], Optional[str]]:
        """Extract and create a recipe from a video URL.

        This method should be overridden by subclasses.

        Args:
            url: Video URL from the platform
            mock: If True, uses mock data instead of real API calls

        Returns:
            Tuple of (recipe in markdown format, thumbnail URL) or (None, None) if no recipe found

        Raises:
            Exception: If any step in the pipeline fails
        """
        raise NotImplementedError("Subclasses must implement _url_to_text_recipe")

    async def _create_text_recipe_with_audio(
        self, audio_file: Path, description: str
    ) -> Optional[str]:
        """Create recipe from audio and description using Voxtral (shared method).

        Args:
            audio_file: Path to extracted audio file
            description: Video description text

        Returns:
            Recipe in markdown format, or None if no recipe found

        Raises:
            Exception: If LLM processing fails or validation fails
        """
        # Get JSON schema from LlmOutputFormat
        json_schema = LlmOutputFormat.model_json_schema()
        str_json_schema = json.dumps(json_schema, indent=2)

        # Format the template with description and schema
        prompt = TemplateFormatter.format_template(
            self.TEMPLATE_PATH, description=description, schema=str_json_schema
        )

        # Call Voxtral API with audio and prompt
        response = await self.mistral_service.call_voxtral_api(
            audio_file_path=audio_file,
            text_prompt=prompt,
            model=self.MODEL,
            json_schema=json_schema,
        )

        if not response:
            raise Exception("No response received from Mistral Voxtral API")

        # Parse and validate the JSON response using Pydantic
        try:
            llm_output = LlmOutputFormat.model_validate_json(response)
            return llm_output.recipe

        except json.JSONDecodeError as e:
            raise Exception(f"Invalid JSON response from LLM: {str(e)}")
        except Exception as e:
            raise Exception(f"LLM response validation failed: {str(e)}")

    async def poll_recipe_status(self, request: PollingRequest) -> PollingResponse:
        """Poll the status of recipe imports.

        For each recipe_id:
        - If in loading_recipes: returns the current status (processing, extracting_techniques, error)
        - If in recipes table: returns "completed"
        - If in neither: returns "error" with message (orphaned state)

        Args:
            request: The request containing recipe_ids list and user_id

        Returns:
            PollingResponse: Dictionary mapping recipe_id to status

        Raises:
            ValueError: If user not found or other errors
        """
        # Get all loading recipes at once (includes timeout check)
        loading_recipes = await self.db_service.get_loading_recipes(request.user_id)

        statuses: dict[str, RecipeStatus] = {}
        error_recipe_ids = []

        for recipe_id in request.recipe_ids:
            # Check if recipe is in loading_recipes dict
            loading_recipe = loading_recipes.get(recipe_id)

            if loading_recipe:
                # Recipe is still loading - return the actual status
                status = loading_recipe.status

                # If error state, mark for removal
                if status == LoadingStatus.ERROR:
                    statuses[recipe_id] = RecipeStatus(
                        status=status,
                        error_message="Recipe import failed",
                    )
                    error_recipe_ids.append(recipe_id)
                else:
                    statuses[recipe_id] = RecipeStatus(status=status)
                continue

            # Check if recipe is in completed recipes
            try:
                stored_recipe = await self.db_service.get_recipe(recipe_id)
                # Create recipe display data from stored recipe
                recipe_display = self.db_service.create_recipe_display(stored_recipe)
                # Recipe exists and is completed
                statuses[recipe_id] = RecipeStatus(
                    status=LoadingStatus.COMPLETED, recipe=recipe_display
                )
            except ValueError:
                # Recipe not in loading and not in recipes - orphaned state
                statuses[recipe_id] = RecipeStatus(
                    status=LoadingStatus.ERROR,
                    error_message="Recipe not found in loading or completed state",
                )

        # Remove all error recipes at once
        for recipe_id in error_recipe_ids:
            await self.db_service.remove_loading_recipe(request.user_id, recipe_id)

        return PollingResponse(statuses=statuses)

    async def _create_text_recipe_with_transcript(
        self, transcript: str = "", description: str = ""
    ) -> Optional[str]:
        """Create recipe from transcript and/or description using Mistral (shared method).

        Args:
            transcript: Extracted transcript text (optional)
            description: Video description text (optional)

        Returns:
            Recipe in markdown format, or None if no recipe found

        Raises:
            ValueError: If both transcript and description are None
            Exception: If LLM processing fails or validation fails
        """
        # Ensure at least one of transcript or description is provided
        if transcript == "" and description == "":
            raise ValueError(
                "At least one of transcript or description must be provided"
            )

        # Get JSON schema from LlmOutputFormat
        json_schema = LlmOutputFormat.model_json_schema()
        str_json_schema = json.dumps(json_schema, indent=2)

        # Format the template with transcript, description, and schema
        prompt = TemplateFormatter.format_template(
            self.TEMPLATE_PATH,
            transcript=transcript or "",
            description=description or "",
            schema=str_json_schema,
        )

        # Call Mistral API with text prompt
        response = await self.mistral_service.call_llm_api(
            input_prompt=prompt, model=self.MODEL, json_schema=json_schema
        )

        if not response:
            raise Exception("No response received from Mistral API")

        # Parse and validate the JSON response using Pydantic
        try:
            llm_output = LlmOutputFormat.model_validate_json(response)
            return llm_output.recipe

        except json.JSONDecodeError as e:
            raise Exception(f"Invalid JSON response from LLM: {str(e)}")
        except Exception as e:
            raise Exception(f"LLM response validation failed: {str(e)}")
